PROBING_API_IMAGE_VERSION="2.0.0-rc2"
PROBING-CALLER_IMAGE_VERSION="2.0.0-rc2"
PROBING-ESERVICE-OPERATIONS_IMAGE_VERSION="2.0.0-rc2"
PROBING-ESERVICE-RESPONSE-UPDATER_IMAGE_VERSION="2.0.0-rc2"
PROBING-SCHEDULER_IMAGE_VERSION="2.0.0-rc2"
PROBING-STATISTICS-API_IMAGE_VERSION="2.0.0-rc2"
PROBING-TELEMETRY-WRITER_IMAGE_VERSION="2.0.0-rc2"

#JOBS
PROBING-ESERVICE-REGISTRY-READER_IMAGE_VERSION="2.0.0-rc2"
PROBING-ESERVICE-REGISTRY-UPDATER_IMAGE_VERSION="2.0.0-rc2"
