apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-eservice-operations
  name: interop-be-probing-eservice-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-eservice-operations
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-eservice-operations
    spec:
      serviceAccountName: interop-be-probing-operations
      containers:
        - image: ghcr.io/pagopa/interop-probing-core/interop-be-probing-eservice-operations:2.0.0-rc2
          name: interop-be-probing-eservice-operations
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: LOG_LEVEL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: AWS_REGION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: DB_NAME
            - name: SCHEMA_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: SCHEMA_NAME
            - name: CORS_ORIGIN_ALLOWED
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: CORS_ORIGIN_ALLOWED
            - name: TOLERANCE_MULTIPLIER_IN_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: TOLERANCE_MULTIPLIER_IN_MINUTES
            - name: POLLING_FREQUENCY_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: POLLING_FREQUENCY_THRESHOLD
            - name: INTEROP_PROBING_OPERATIONS_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-operations
                  key: INTEROP_PROBING_OPERATIONS_APP_NAME
            - name: FLYWAY_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: interop-be-probing-aurora-flyway-user-credentials
                  key: FLYWAY_DATABASE_USERNAME
            - name: FLYWAY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: interop-be-probing-aurora-flyway-user-credentials
                  key: FLYWAY_DATABASE_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: interop-be-probing-app-aurora-user-credentials
                  key: DATABASE_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: interop-be-probing-app-aurora-user-credentials
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 8080
              name: http
status: {}
