apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
- ../../../base/configMap
- ../../../base/deployment
patches:
  - path: configMap.yaml
    target:
      kind: ConfigMap
    options:
      allowNameChange: true
      allowKindChange: false
  - path: deployment.yaml
    target:
      kind: Deployment
    options:
      allowNameChange: true
      allowKindChange: false