apiVersion: batch/v1
kind: CronJob
metadata:
  name: interop-be-probing-eservice-registry-updater
  labels:
    app: interop-be-probing-eservice-registry-updater
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: interop-be-probing-eservice-registry-updater
        spec:
          serviceAccountName: interop-be-probing-eservice-registry-updater
          restartPolicy: Never
          containers:
            - name: interop-be-probing-eservice-registry-updater
              image: ghcr.io/pagopa/interop-be-probing/interop-be-probing-eservice-registry-updater:develop
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 500m
                  memory: 512Mi
              env:
                - name: LOG_LEVEL
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-common
                      key: LOG_LEVEL
                - name: AWS_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-common
                      key: AWS_REGION
                - name: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-common
                      key: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
                - name: API_OPERATIONS_BASEURL
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-common
                      key: API_OPERATIONS_BASEURL
                - name: SQS_ENDPOINT_SERVICES_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: SQS_ENDPOINT_SERVICES_QUEUE
                - name: INTEROP_PROBING_ESERVICE_REGISTRY_UPDATER_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: INTEROP_PROBING_ESERVICE_REGISTRY_UPDATER_NAME