apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uat
resources:
- ../../../base/configMap
- ../../../base/deployment
- ../../../base/svc
- ../../../base/ingress
- ../../../base/hpa
patches:
  - path: configMap.yaml
    target:
      kind: ConfigMap
    options:
      allowNameChange: true
      allowKindChange: false
  - path: svc.yaml
    target:
      kind: Service
    options:
      allowNameChange: true
      allowKindChange: false
  - path: ingress.yaml
    target:
      kind: Ingress
    options:
      allowNameChange: true
      allowKindChange: false
  - path: deployment.yaml
    target:
      kind: Deployment
    options:
      allowNameChange: true
      allowKindChange: false
  - path: hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
    options:
      allowNameChange: true
      allowKindChange: false