apiVersion: v1
data:
  API_OPERATIONS_BASEURL: http://interop-be-probing-eservice-operations.dev.svc.cluster.local/
  API_OPERATIONS_ESERVICE_BASEPATH: eservices
  API_OPERATIONS_PRODUCER_BASEPATH: producers
kind: ConfigMap
metadata:
  name: interop-be-probing-common