apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-telemetry-writer
  name: interop-be-probing-telemetry-writer
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-telemetry-writer
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-telemetry-writer
    spec:
      serviceAccountName: interop-be-probing-telemetry-writer
      containers:
      - image: ghcr.io/pagopa/interop-be-probing-telemetry-writer1.0.0-rc
        name: interop-be-probing-telemetry-writer
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-common
                key: AWS_XRAY_DAEMON_ADDRESS
          - name: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
          - name: TIMESTREAM_DATABASE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_DATABASE
          - name: TIMESTREAM_TABLE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_TABLE
          - name: TIMESTREAM_RETRIES
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_RETRIES
          - name: TIMESTREAM_MAX_CONNECTIONS
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_MAX_CONNECTIONS  
          - name: TIMESTREAM_ATTEMPT_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_ATTEMPT_TIMEOUT
          - name: INTEROP_PROBING_TELEMETRY_WRITER_NAME
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: INTEROP_PROBING_TELEMETRY_WRITER_NAME                                              
status: {}
