apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: interop-be-probing-telemetry-writer
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interop-be-probing-telemetry-writer
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80