apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-telemetry-writer
  name: interop-be-probing-telemetry-writer
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-telemetry-writer
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-telemetry-writer
    spec:
      serviceAccountName: interop-be-probing-telemetry-writer
      containers:
      - image: amazon/aws-xray-daemon:3.3.7
        imagePullPolicy: Always
        name: xray-daemon
        ports:
        - containerPort: 2000
          protocol: UDP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 50Mi
      - image: ghcr.io/pagopa/interop-be-probing-telemetry-writer:develop
        name: interop-be-probing-telemetry-writer
        resources: {}
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: localhost:2000
          - name: SQS_ENDPOINT_TELEMETRY_QUEUE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: SQS_ENDPOINT_TELEMETRY_QUEUE
          - name: TIMESTREAM_DATABASE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_DATABASE
          - name: TIMESTREAM_TABLE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_TABLE
          - name: TIMESTREAM_RETRIES
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_RETRIES
          - name: TIMESTREAM_MAX_CONNECTIONS
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_MAX_CONNECTIONS  
          - name: TIMESTREAM_ATTEMPT_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-telemetry-writer
                key: TIMESTREAM_ATTEMPT_TIMEOUT                                             
status: {}
