apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/configMap
- ../../../base/deployment
patches:
  - path: configMap.yaml
    target:
      kind: ConfigMap
    options:
      allowNameChange: true
      allowKindChange: true
  - path: deployment.yaml
    target:
      kind: ConfigMap
    options:
      allowNameChange: true
      allowKindChange: true