apiVersion: v1
data:
  DATABASE_URL: jdbc:postgresql://interop-probing-operational-database-dev.cluster-caudw4yuwazj.eu-central-1.rds.amazonaws.com:5432/interop_probing_operational?currentSchema=interop_probing_operational
  DATABASE_DRIVER: org.postgresql.Driver
  DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQL95Dialect
  DATABASE: POSTGRESQL
  JDBC_TIME_ZONE: UTC
  VALIDATE_MIGRATION_NAMING: "true"
  SCHEMA_NAME: interop_probing_operational
  CORS_ORIGIN_ALLOWED: "*"
kind: ConfigMap
metadata:
  name: interop-be-probing-api
---
apiVersion: v1
data:
  API_OPERATIONS_BASEURL: interop-be-probing-eservice-operations.dev.svc.cluster.local/
  API_ESERVICE_BASEPATH: eservices
  API_PRODUCER_BASEPATH: producers
kind: ConfigMap
metadata:
  name: interop-be-probing-common
---
apiVersion: v1
data:
  DATABASE_URL: jdbc:postgresql://interop-probing-operational-database-dev.cluster-caudw4yuwazj.eu-central-1.rds.amazonaws.com:5432/interop_probing_operational?currentSchema=interop_probing_operational
  DATABASE_DRIVER: org.postgresql.Driver
  DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQL95Dialect
  DATABASE: POSTGRESQL
  JDBC_TIME_ZONE: UTC
  VALIDATE_MIGRATION_NAMING: "true"
  SCHEMA_NAME: interop_probing_operational
kind: ConfigMap
metadata:
  name: interop-be-probing-eservice-operations
---
apiVersion: v1
data:
  S3_BUCKET_KEY: eservices.json
  S3_BUCKET_NAME: interop-probing-eservices-dev
  SQS_ENDPOINT_SERVICES_QUEUE: https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_registry_queue.fifo
kind: ConfigMap
metadata:
  name: interop-be-probing-eservice-registry-reader
---
apiVersion: v1
data:
  SQS_ENDPOINT_SERVICES_QUEUE: https://sqs.eu-central-1.amazonaws.com/774300547186/eservice_registry_queue.fifo
  JDBC_URL: jdbc:postgresql://interop-probing-operational-database-dev.cluster-caudw4yuwazj.eu-central-1.rds.amazonaws.com:5432/interop_probing_operational?currentSchema=interop_probing_operational
  PERSIST_UNIT_NAME: interop-db-pu
kind: ConfigMap
metadata:
  name: interop-be-probing-eservice-registry-updater