apiVersion: batch/v1
kind: CronJob
metadata:
  name: interop-be-probing-eservice-registry-reader
  labels:
    app: interop-be-probing-eservice-registry-reader
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: interop-be-probing-eservice-registry-reader
        spec:
          serviceAccountName: interop-be-probing-eservice-registry-reader
          containers:
            - name: interop-be-probing-eservice-registry-reader
              image: ghcr.io/pagopa/interop-be-probing-eservice-registry-reader:develop
              imagePullPolicy: Always
              env:
                - name: S3_BUCKET_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-reader
                      key: S3_BUCKET_NAME
                - name: S3_BUCKET_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-reader
                      key: S3_BUCKET_KEY
                - name: SQS_ENDPOINT_SERVICES_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-reader
                      key: SQS_ENDPOINT_SERVICES_QUEUE
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: interop-be-probing-eservice-registry-updater
  labels:
    app: interop-be-probing-eservice-registry-updater
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: interop-be-probing-eservice-registry-updater
        spec:
          serviceAccountName: interop-be-probing-eservice-registry-updater
          containers:
            - name: interop-be-probing-eservice-registry-updater
              image: ghcr.io/pagopa/interop-be-probing-eservice-registry-updater:develop
              imagePullPolicy: Always
              env:
                - name: API_OPERATIONS_BASEURL
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-common
                      key: API_OPERATIONS_BASEURL
                - name: SQS_ENDPOINT_SERVICES_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: SQS_ENDPOINT_SERVICES_QUEUE
                - name: JDBC_URL
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: JDBC_URL
                - name: PERSIST_UNIT_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: PERSIST_UNIT_NAME                   
                - name: JDBC_USERNAME 
                  valueFrom:
                    secretKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: JDBC_USERNAME
                - name: JDBC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: interop-be-probing-eservice-registry-updater
                      key: JDBC_PASSWORD  
          restartPolicy: Never