apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: add
      path: /metadata/annotations/reloader.stakater.com~1search
      value: true
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /metadata/annotations/reloader.stakater.com~1match
      value: true
  target:
    kind: ConfigMap
resources:
- deployments.yaml
- configMaps.yaml
- cronJobs.yaml
- svcs.yaml
- ingresses.yaml