PROBING_API_IMAGE_VERSION="develop"
PROBING-CALLER_IMAGE_VERSION="develop"
PROBING-ESERVICE-OPERATIONS_IMAGE_VERSION="develop"
PROBING-ESERVICE-RESPONSE-UPDATER_IMAGE_VERSION="develop"
PROBING-SCHEDULER_IMAGE_VERSION="develop"
PROBING-STATISTICS-API_IMAGE_VERSION="develop"
PROBING-TELEMETRY-WRITER_IMAGE_VERSION="develop"

#JOBS
PROBING-ESERVICE-REGISTRY-READER_IMAGE_VERSION="develop"
PROBING-ESERVICE-REGISTRY-UPDATER_IMAGE_VERSION="develop"
