apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-api
  name: interop-be-probing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-api
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-api
    spec:
      serviceAccountName: interop-be-probing-api
      containers:
        - image: ghcr.io/pagopa/interop-probing-core/interop-be-probing-api:2.0.0-rc1
          name: interop-be-probing-api
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-api
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-api
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: LOG_LEVEL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: AWS_REGION
            - name: API_OPERATIONS_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: API_OPERATIONS_BASEURL
            - name: TOLERANCE_MULTIPLIER_IN_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-api
                  key: TOLERANCE_MULTIPLIER_IN_MINUTES
            - name: CORS_ORIGIN_ALLOWED
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-api
                  key: CORS_ORIGIN_ALLOWED
            - name: INTEROP_PROBING_API_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-api
                  key: INTEROP_PROBING_API_APP_NAME
          ports:
            - containerPort: 8080
              name: http
status: {}
