apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
patches:
  - path: configMap.yaml
    target:
      kind: ConfigMap
    options:
      allowNameChange: true
      allowKindChange: true
  - path: cronJob.yaml
    target:
      kind: CronJob
    options:
      allowNameChange: true
      allowKindChange: true