apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-eservice-registry-caller
  name: interop-be-probing-eservice-registry-caller
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-eservice-registry-caller
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-eservice-registry-caller
    spec:
      serviceAccountName: interop-be-probing-caller
      containers:
      - image: ghcr.io/pagopa/interop-be-probing-caller:develop
        name: interop-be-probing-eservice-registry-caller
        resources: {}
        env:
          - name: SQS_ENDPOINT_POLL_QUEUE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-eservice-registry-caller
                key: SQS_ENDPOINT_POLL_QUEUE
          - name: SQS_ENDPOINT_POLL_RESULT_QUEUE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-eservice-registry-caller
                key: SQS_ENDPOINT_POLL_RESULT_QUEUE    
          - name: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-eservice-registry-caller
                key: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE                                                            
        ports: 
          - containerPort: 8080
            name: http
status: {}