apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-response-updater
  name: interop-be-probing-response-updater
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-response-updater
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-response-updater
    spec:
      serviceAccountName: interop-be-probing-response-updater
      containers:
      - image: amazon/aws-xray-daemon:3.3.7
        imagePullPolicy: Always
        name: xray-daemon
        ports:
        - containerPort: 2000
          protocol: UDP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 50Mi
      - image: ghcr.io/pagopa/interop-be-probing-response-updater:develop
        name: interop-be-probing-response-updater
        resources: {}
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: localhost:2000
          - name: API_OPERATIONS_ESERVICE_BASEPATH
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-common
                key: API_OPERATIONS_ESERVICE_BASEPATH
          - name: API_OPERATIONS_PRODUCER_BASEPATH
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-common
                key: API_OPERATIONS_PRODUCER_BASEPATH
          - name: API_OPERATIONS_BASEURL
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-common
                key: API_OPERATIONS_BASEURL
          - name: SQS_ENDPOINT_POLL_RESULT_QUEUE
            valueFrom:
              configMapKeyRef:
                name: interop-be-probing-response-updater
                key: SQS_ENDPOINT_POLL_RESULT_QUEUE                                                
        ports: 
          - containerPort: 8080
            name: http
status: {}
