apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../../base/deployment
- ../../../base/configMap
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
    options:
      allowNameChange: true
      allowKindChange: false
  - path: configMap.yaml
    target:
      kind: ConfigMap
    options:
      allowNameChange: true
      allowKindChange: false

