apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interop-be-probing-eservice-registry-caller
  name: interop-be-probing-eservice-registry-caller
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-be-probing-eservice-registry-caller
  strategy: {}
  template:
    metadata:
      labels:
        app: interop-be-probing-eservice-registry-caller
    spec:
      serviceAccountName: interop-be-probing-caller
      containers:
        - image: ghcr.io/pagopa/interop-be-probing/interop-be-probing-caller:develop
          name: interop-be-probing-eservice-registry-caller
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: AWS_XRAY_DAEMON_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: AWS_XRAY_DAEMON_ADDRESS
            - name: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: CONSUMER_POLLING_TIMEOUT_IN_SECONDS
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: LOG_LEVEL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-common
                  key: AWS_REGION
            - name: SQS_ENDPOINT_POLL_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: SQS_ENDPOINT_POLL_QUEUE
            - name: SQS_ENDPOINT_POLL_RESULT_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: SQS_ENDPOINT_POLL_RESULT_QUEUE
            - name: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE
            - name: JWT_PAYLOAD_EXPIRE_TIME_IN_SEC
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: JWT_PAYLOAD_EXPIRE_TIME_IN_SEC
            - name: JWT_PAYLOAD_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: JWT_PAYLOAD_ISSUER
            - name: JWT_PAYLOAD_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: JWT_PAYLOAD_SUBJECT
            - name: JWT_PAYLOAD_KID_KMS
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: JWT_PAYLOAD_KID_KMS
            - name: INTEROP_PROBING_CALLER_NAME
              valueFrom:
                configMapKeyRef:
                  name: interop-be-probing-eservice-registry-caller
                  key: INTEROP_PROBING_CALLER_NAME
status: {}
