apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: interop-be-probing-eservice-registry-caller
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interop-be-probing-eservice-registry-caller
  targetCPUUtilizationPercentage: 80